#version: '3.8'
#https://github.com/JAlcocerT/Docker/tree/main/AI_Gen/Project_YT_Groq
services:
  phidata_service:
    image: ghcr.io/jalcocert/phidata:yt-groq #phidata:yt_summary_groq
    container_name: phidata_yt_groq
    ports:
      - "8502:8501"    
    environment:
      - GROQ_API_KEY=your_api_key_here # your_api_key_here 🖕
      - AVAILABLE_LLM_MODELS = deepseek-r1-distill-llama-70b,qwen-qwq-32b,llama-3.3-70b-versatile,llama-3.1-8b-instant,gemma2-9b-it,llama3-70b-8192
    #command: tail -f /dev/null 
    command: streamlit run cookbook/llms/groq/video_summary/app_v3.py
#     networks:
#       - cloudflare_tunnel
            
# networks:
#   cloudflare_tunnel:
#     external: true        


#docker exec -it phidata_yt_groq /bin/bash
#podman exec -it phidata_yt_groq /bin/bash

# cd ./cookbook/llms/groq/video_summary
# streamlit run app.py